<?php
/**
 * @category    design
 * @package     monster_default
 * @copyright   Copyright (c) 2012 Monster Market. (http://www.monstermarket.com)
 */
?>


<footer class="footer-bottom-container sellyours-footer-container">
    <div class="footer-bottom">
    	<ul>
    		<li><a href="#"><?php echo Mage::helper('udropship')->__('Browse All Products')?></a></li>
    		<li><a href="<?php echo $this->getUrl('udsell/index/sellsearch')?>"><?php echo Mage::helper('udropship')->__('Sell with Us')?></a></li>
    		<li><a href="#"><?php echo Mage::helper('udropship')->__('Help')?></a></li>
    		<li><a href="#"><?php echo Mage::helper('udropship')->__('RSS')?></a></li>
    	</ul>
    	<p class="copyright">&copy; 2012 <?php echo Mage::helper('udropship')->__('Monster Market')?>. <?php echo Mage::helper('udropship')->__('All rights reserved.')?>
    		<span class="pipe">|</span><a href="#"><?php echo Mage::helper('udropship')->__('Privacy Policy')?></a>
    		<span class="pipe">|</span><a href="#"><?php echo Mage::helper('udropship')->__('Terms of Use')?></a>
    	</p>
    </div>
</footer>