<?php
/**
 * @category    design
 * @package     monster_default
 * @copyright   Copyright (c) 2011 Monster Market. (http://www.monstermarket.com)
 */
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    if ($_product) {
	    $_v = Mage::helper('udropship')->getVendor($_product);
	} else {
	    $_v = Mage::helper('umicrosite')->getCurrentVendor();
	}
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view product-sell-view">
    <div class="product-sell-header generic-box">
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
    	<span class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(80)?>" width="80" height="80" alt="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"/></span>
        <div class="product-name">
            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
        </div>
        <p>#<?php echo $_product->getSku(); ?></p>
    </div>
	<div class="product-sell-content">
    	<?php echo $this->getChildHtml('product.sell') ?>
	</div>
</div>
