<?php
$itemOption = $this->getData('item');
$buyRequest = $itemOption->getBuyRequest()->getData();
$jsonFilename = $buyRequest['extra_options'];
$images = Mage::helper('pdp')->getThumbnailImage($jsonFilename);
if(empty($images)) {
	return;
}
?>
<?php echo $this->getLayout()->createBlock("core/template")->setTemplate("pdp/action/load_fonts.phtml")->toHtml() ?>
<dt><span style="font-weight: bold"><?php echo $this->__('Customize Design') ?></span></dt>
<dl class="item-options pdp_cart_item">
<?php foreach ($images as $image) : ?>
	<dt><?php echo $this->__($image['name']) ?></dt>
	<dd><div class="pdc-preview-item" style="border: 1px solid #ccc;line-height: 0;width: 180px;"><?php echo $image['image'] ?></div></dd>
<?php endforeach; ?>
</dl>